### ISSUE TITLE
Reveal code manually, one line at a time.

### ISSUE THREAD

**Issue by WadeWaldron** [glorious-codes/glorious-demo#118]
It might be nice to have a feature where rather than automatically typing out the code all at once, you could trigger it to reveal one line at a time (say every time you press enter or space).

This would allow for a more controlled demo experience if required.

**Comment by rafaelcamargo** [comment]
Hey @WadeWaldron!

This library was actually conceived to play an animation automatically, without any human control besides the JavaScript code previously written. The purpose of the library is to automatically present code snippets on websites, not to behave as a kind of slideshow to be presented to a crowd. So, this issue misses the original purpose of the library.

One suggestion for your use case would be to simply record the animation with any screen recording tool and then play it for the crowd.
