### ISSUE TITLE
Provide a referrence sheet and an examples page on the website.

### ISSUE THREAD

**Issue by maximousblk** [glorious-codes/glorious-demo#23]

**Comment by rafaelcamargo** [comment]
Hey Maximous! I'm not sure I am seeing your point.

### Reference Sheet

About the reference sheet, you have all the details about the API explained on the README of this project. [See it here](https://github.com/glorious-codes/glorious-demo#basic-usage).

### Examples

About examples, the [Glorious Demo Page](https://glorious.codes/demo) itself is a live example. You can even go further and edit the example played on the page clicking on *Edit* button:

![example-edit-btn](https://user-images.githubusercontent.com/4738687/47954014-da2def80-df63-11e8-8e4a-d8cac85821e5.png)

After clicking on the button, you'll see exactly the code that generates that demo:

![example-code](https://user-images.githubusercontent.com/4738687/47954035-1b260400-df64-11e8-910e-e2ffe6485e4e.png)

Having access to the demo's code, you change change anything and see the result clicking on the *Preview* button. You can even share your just generated demo with your friends clicking on the *Copy Demo Link* button.

That said, I'm closing this for now. If you need any help on using the lib, please let me know 👍
