### ISSUE TITLE
npm run build failure

### ISSUE THREAD

**Issue by zfrisch** [glorious-codes/glorious-demo#27]
It seems like your build script isn't working. After cloning and installing, the npm run build command will initially tell you that it won't work because the script is just a filepath, not a command. After changing this to `node ./node_modules/whatever/webpack.js` the build script will still fail. Thoughts?

**Comment by rafaelcamargo** [comment]
Hello *zfrisch*!

The `npm run build` of the project is just an alias for `./node_modules/webpack/bin/webpack.js`.
As you can see on the last build at [CircleCI](https://circleci.com/gh/glorious-codes/glorious-demo/49), the build command is working properly.

**My local config:**
Node v8.9.4
NPM v5.6.0

If you perform [these steps](https://github.com/glorious-codes/glorious-demo#contributing), it should work.

Feel free to reopen the issue if you still have any problem 👍
