### ISSUE TITLE
Improve white space on terminal application

### ISSUE THREAD

**Issue by heowc** [glorious-codes/glorious-demo#36]
hello, @rafaelcamargo 

Thanks for creating [glorious-demo](https://github.com/glorious-codes/glorious-demo).

I used [glorious-demo](https://github.com/glorious-codes/glorious-demo) on [my blog](https://heowc.github.io/2018/01/08/spring-boot-start/).

And I found a problem. There is no problem with `editor` type, but `terminal` type does not represent white space.

I used a temporary `<span style =' white-space: pre '> ... </ span>` to solve this problem. But I think there is a better way.

### example
```html
<html>
<head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@glorious/demo@0.7.0/dist/gdemo.min.css">
</head>
<body>
<div id="container"></div>

<script src="https://cdn.jsdelivr.net/npm/@glorious/demo@0.7.0/dist/gdemo.min.js"></script>
<script>
const demo = new GDemo('#container');

const code = `
function greet(){
    console.log("Hello World!");
}

greet();
`;

demo
    .openApp('terminal', {minHeight: '350px', promptString: '$'})
    .command('cat demo.js', {onCompleteDelay: 500})
    .respond(code)
    .command('')
    .end();

</script>
</body>
</html>
```

### result

```text
$ cat demo.js
function greet(){
console.log("Hello World!");
}

greet();
```

+) I will make hexo tag library of [glorious-demo](https://github.com/glorious-codes/glorious-demo). how about you?

**Comment by rafaelcamargo** [comment]
Interesting point @heowc

I have never noticed that, but the implementation is really easy to get done. I have just planned it and, asap, I'll try release that 👍 

Regarding Hexo, I'll be very happy in seeing your lib 😃

**Comment by heowc** [comment]
Thanks a lot. +1

**Comment by mostafaebrahimi** [comment]
@rafaelcamargo I guess you must add `white-space pre !important` to `.terminal-response-line-text` in `src\styles\terminal-response-line.styl`.<br>But there is one problem and that is different between code response and terminal response.(we expect `white-space pre` in code samples but not in terminal responses).<br>So I think it's better to be selected by client [like @heowc :)] or implement two types of responses

**Comment by rafaelcamargo** [comment]
Well noticed @mostafaebrahimi!

My strategy would basically be:
1 - I prefer not to use `!important`. I consider it a violation of the Open Close principle.
2 - I was thinking to consider `white-space: pre` only for plain text responses. I would not consider it for html responses, since the client should be 100% free when he decides to respond with a HTML string.

What d'you think about this?

**Comment by mostafaebrahimi** [comment]
@rafaelcamargo I think it's a better way.
My opinion is to some changes in `components\terminal-response-line\terminal-response-line.js`<br>

1 - change
```javascript
function appendText(container, text){
  container.innerText = text;
  container.classList.add('terminal-response-plain-text')
}
```
3 -  change
```javascript
function appendHtml(container, html){
  container.appendChild(html);
  container.classList.add('terminal-response-html-text')
}
```
What do you think about these changes?

**Comment by rafaelcamargo** [comment]
@mostafaebrahimi The general idea would be exactly that. 👍
I would just avoid repeating `classList.add`:

``` javascript
function appendText(container, text){
  container.innerText = text;
  addElementCssClass(container, 'terminal-response-plain-text');
}

function appendHtml(container, html){
  container.appendChild(html);
  addElementCssClass(container, 'terminal-response-html-text');
}

function addElementCssClass(element, cssClass){
  element.classList.add(cssClass);
}
```

**Comment by mostafaebrahimi** [comment]
@rafaelcamargo Great 💯
