### ISSUE TITLE
Chinese with your README.md + Wiki, if you like :)

### ISSUE THREAD

**Issue by chinanf-boy** [glorious-codes/glorious-demo#38]
## Translation

- https://github.com/chinanf-boy/glorious-demo-zh
- https://github.com/chinanf-boy/glorious-demo-zh/wiki

**Comment by rafaelcamargo** [comment]
Hello @chinanf-boy!

First of all, sorry for my late reply.
Regarding your contribution, I am very glad of it. Never ever imagined someone in China would translate the docs for Glorious Demo!
However, offering documentation in more than one language demands an additional effort to keep things updated. That said, I have to confess that I am a little afraid that at some point, the non-english documentation may become not as precise as it should be and, then, may lead someone to a bad experience at all.

So, at least for now, I'll prefer keeping with just english. Anayway, congrats for your job 👍
