### ISSUE TITLE
Is it for programming video teaching video tutorial?

### ISSUE THREAD

**Issue by dragen1860** [glorious-codes/glorious-demo#53]
Dear author:
  i'm  teaching programming in video tutorial. And i want to show code in slides in an elegant and interactive way.
Current I found [Carbon](https://carbon.now.sh/?bg=rgba(171%2C%20184%2C%20195%2C%201)&t=cobalt&wt=none&l=text%2Fx-c%2B%2Bsrc&ds=true&dsyoff=20px&dsblur=68px&wc=true&wa=true&pv=56px&ph=56px&ln=false&fm=Hack&fs=14px&lh=133%25&si=false&es=2x&wm=false) is good enough to show static code image in an element way. However it's static and can not show code animation line by line , or paragraph by paragraph.

I find your great `Glorious` tool can show code in an interactive way. and I have some questions.
1. Can Glorious export the animation to a gif file? so that i can embed it in ms office.
2.  Can I control the line or paragraph show time? i mean, can i set it show after n seconds, or even show it after i click?
3. Can i easily export a gif of a file by giving  any source file?

Thank you.

**Comment by rafaelcamargo** [comment]
Hello, @dragen1860!

Let me see if I can help you:

1. The idea of Glorious Demo was in fact to avoid having to generate a .gif to show it on a website. Differently from a gif, you can build your animation with just HTML/CSS/JS using [Glorious Demo API](https://github.com/glorious-codes/glorious-demo#api). That said, it's not possible to export the animation built as a .gif. If you really need a .gif, I'd recommend to build your animation using Glorious Demo and, then, record your screen using [Giphy](https://giphy.com/apps/giphycapture) or [Gifox](https://gifox.io/).
2. Yes. For every step of your animation you can pass an option called `onCompleteDelay`. Doing so, the next step of your animation will delay the amount of milliseconds you set on the previous step before to be played. In [this example](https://glorious.codes/demo?demo=Y29uc3QgZ2RlbW8gPSBuZXcgR0RlbW8oJ1tkYXRhLWRlbW8tY29udGFpbmVyXScpOwoKY29uc3QgZmlyc3RGdW5jdGlvbiA9IGBmdW5jdGlvbiBmaXJzdCgpJU9QQlIlCiAgLy8gZmlyc3QgZnVuY3Rpb24gcGxheWVkIGltbWVkaWF0ZWx5LgolQ0xCUiVgCgpjb25zdCBzZWNvbmRGdW5jdGlvbiA9IGBmdW5jdGlvbiBzZWNvbmQoKSVPUEJSJQogIC8vIHNlY29uZCBmdW5jdGlvbiBwbGF5ZWQgYWZ0ZXIgNSBzZWNvbmRzLgolQ0xCUiUKYAoKZnVuY3Rpb24gaGlnaGxpZ2h0Q29kZShjb2RlKSVPUEJSJQogIHJldHVybiBQcmlzbS5oaWdobGlnaHQoCiAgICBjb2RlLAogICAgUHJpc20ubGFuZ3VhZ2VzLmphdmFzY3JpcHQsCiAgICAnamF2YXNjcmlwdCcKICApOwolQ0xCUiUKCmdkZW1vLm9wZW5BcHAoJ2VkaXRvcicsICVPUEJSJSBtaW5IZWlnaHQ6ICc0MDBweCcsIHdpbmRvd1RpdGxlOiAnZGVtby5qcycgJUNMQlIlKQogIC53cml0ZShoaWdobGlnaHRDb2RlKGZpcnN0RnVuY3Rpb24pLCAlT1BCUiUgb25Db21wbGV0ZURlbGF5OiA1MDAwICVDTEJSJSkKICAud3JpdGUoaGlnaGxpZ2h0Q29kZShzZWNvbmRGdW5jdGlvbikpCiAgLmVuZCgpOwo=), I have written the first function immediately and waited 5 seconds before writing the second one.
3. As explained on the answer 1, no.

I hope this answer to be useful for you. In case you have more doubts, don't hesitate to ask me 👍 
Have a nice day!

**Comment by dragen1860** [comment]
Thank you. It helps a lot!
