### ISSUE TITLE
write() doesn't honor code highlighted with Prism

### ISSUE THREAD

**Issue by FoamScience** [glorious-codes/glorious-demo#63]
Hi @rafaelcamargo,

First, thanks for the great package; look what I did it with it in around a half-an-hour:
[Code Demo App](https://github.com/FoamScience/CodeDemoApp)

But, now I'm facing a problem with the editor's `write()` method, it renders the highlighted code
as plain HTML ...

![Sample Code demo app usage](https://user-images.githubusercontent.com/34474472/74237596-34c00a80-4cd4-11ea-8719-fd8e30efdea6.gif)

The code I'm trying to show:
```
function name () {doSomething();}
```

### What I verified was:
 
- This has nothing to do with the position of the container (nor its styling apparently)
- The terminal app works fine
- The text to be highlighted is pulled out of a YAML file, but putting it in a `const code` as is produces the same output.

### What I suspect to cause the problem:

Maybe nesting things in a function. Check [How I'm doing this](https://github.com/FoamScience/CodeDemoApp/blob/433d8f71eb6dc305ff85e35591cd603a8ce438e5/window.js#L33).
It's likely that passing `demo` as an argument like this is causing this issue but I don't know how to debug this kind of stuff :cry: 

I hope you could help me figure out what I'm missing here; and thanks in advance

**Comment by rafaelcamargo** [comment]
Hey @FoamScience! Very glad you liked it 🍻 

At a first glance, seemed that you're not using the latest version of the lib.
I just open a [Pull Request](https://github.com/FoamScience/CodeDemoApp/pull/1) in your project.

Best!

**Comment by FoamScience** [comment]
Can't believe I didn't think of that! Thank you so much
