### ISSUE TITLE
Span height issue creating mini vertical scroll

### ISSUE THREAD

**Issue by aleksandr-smechov** [glorious-codes/glorious-demo#70]
The default **span.cursor** class has a height of **24px**.

![image](https://user-images.githubusercontent.com/35517862/79631033-218e4880-8124-11ea-8197-087b55ef038e.png)

I found this creates these weird mini vertical scroll bars when writing to an editor.

![image](https://user-images.githubusercontent.com/35517862/79631052-57cbc800-8124-11ea-8a01-6930423ced1a.png)

Changing **span.cursor** to a height of **16px** fixed the issue.

![image](https://user-images.githubusercontent.com/35517862/79631071-82b61c00-8124-11ea-9ffd-62c52d9859a7.png)

**Comment by rafaelcamargo** [comment]
Hey @aleksandr-smechov! Could you tell me which OS and Browser you're using?

Thanks for let me know about this.

**Comment by aleksandr-smechov** [comment]
Sure, Ubuntu 18.04, latest Firefox (same thing on Chrome on Ubuntu)

**Comment by rafaelcamargo** [comment]
Hey @aleksandr-smechov! Sorry for the late response, but I just released a new version of the library (0.11.3) containing an attempt to fix the bug you reported.

I tried to test it on Linux, but I couldn't... So I'd love if you could update your glorious demo version and tell me if my attempt really fixes that bug.

Thanks is advance for your support 🙂

**Comment by rafaelcamargo** [comment]
Seems that the error has gone:

**Preview**
![image](https://user-images.githubusercontent.com/4738687/107671494-aaa5db80-6c72-11eb-9a97-6fd28e52e970.png)
